### ISSUE TITLE
Incompatible with 1.19.3

### ISSUE THREAD

**Issue by The-Nyla** [FluorideHistorian/WorldDownloader-Fabric#1]
Upon starting this mod on 1.19.3 with the normal fabric loader it says that this mod is not compatible with 1.19.3, I was just wondering if this mod will have 1.19.3 support in the future, thanks!

**Comment by FluorideHistorian** [comment]
this mod is for beta 1.7.3 and nearly abandonware at this point
i doubt we will support 1.19.3 but who knows
